// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payment.Infrastructure.Persistence;

#nullable disable

namespace Payment.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804104331_AddWebhookEvents")]
    partial class AddWebhookEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payment.Domain.Entities.CardToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("integer");

                    b.Property<string>("LastFour")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.ToTable("CardTokens");
                });

            modelBuilder.Entity("Payment.Domain.Entities.PaymentIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("IdempotencyKey");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("PaymentIntents");
                });

            modelBuilder.Entity("Payment.Domain.Entities.PaymentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PaymentLinks");
                });

            modelBuilder.Entity("Payment.Domain.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("Payment.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Processed");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Payment.Domain.Entities.PaymentIntent", b =>
                {
                    b.OwnsOne("Payment.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PaymentIntentId");

                            b1.ToTable("PaymentIntents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.OwnsOne("Payment.Domain.ValueObjects.GatewayReference", "GatewayReference", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("GatewayReference");

                            b1.HasKey("PaymentIntentId");

                            b1.ToTable("PaymentIntents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.OwnsMany("Payment.Domain.Entities.Transaction", "Transactions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("IdempotencyKey")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("PaymentIntentId", "IdempotencyKey")
                                .IsUnique();

                            b1.ToTable("Transactions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");

                            b1.OwnsOne("Payment.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("TransactionId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("Currency");

                                    b2.HasKey("TransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("TransactionId");
                                });

                            b1.OwnsOne("Payment.Domain.ValueObjects.GatewayReference", "GatewayReference", b2 =>
                                {
                                    b2.Property<Guid>("TransactionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("TransactionGatewayRef");

                                    b2.HasKey("TransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("TransactionId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();

                            b1.Navigation("GatewayReference");
                        });

                    b.OwnsOne("Payment.Domain.ValueObjects.AuthorizationCode", "AuthorizationCode", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AuthorizationCode");

                            b1.HasKey("PaymentIntentId");

                            b1.ToTable("PaymentIntents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.OwnsOne("Payment.Domain.ValueObjects.CardDetails", "CardDetails", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CardBrand");

                            b1.Property<string>("LastFour")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("CardLastFour");

                            b1.Property<string>("Token")
                                .HasColumnType("text")
                                .HasColumnName("CardToken");

                            b1.HasKey("PaymentIntentId");

                            b1.ToTable("PaymentIntents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("AuthorizationCode");

                    b.Navigation("CardDetails");

                    b.Navigation("GatewayReference");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Payment.Domain.Entities.PaymentLink", b =>
                {
                    b.OwnsOne("Payment.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentLinkId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PaymentLinkId");

                            b1.ToTable("PaymentLinks");

                            b1.WithOwner()
                                .HasForeignKey("PaymentLinkId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
