// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payment.Infrastructure.Persistence;

#nullable disable

namespace Payment.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payment.Domain.Entities.PaymentIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PaymentIntents");
                });

            modelBuilder.Entity("Payment.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Payment.Domain.Entities.PaymentIntent", b =>
                {
                    b.OwnsOne("Payment.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PaymentIntentId");

                            b1.ToTable("PaymentIntents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.OwnsOne("Payment.Domain.ValueObjects.GatewayReference", "GatewayReference", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("GatewayReference");

                            b1.HasKey("PaymentIntentId");

                            b1.ToTable("PaymentIntents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.OwnsMany("Payment.Domain.Entities.Transaction", "Transactions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("PaymentIntentId");

                            b1.ToTable("Transactions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");

                            b1.OwnsOne("Payment.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("TransactionId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("Currency");

                                    b2.HasKey("TransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("TransactionId");
                                });

                            b1.OwnsOne("Payment.Domain.ValueObjects.GatewayReference", "GatewayReference", b2 =>
                                {
                                    b2.Property<Guid>("TransactionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("TransactionGatewayRef");

                                    b2.HasKey("TransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("TransactionId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();

                            b1.Navigation("GatewayReference");
                        });

                    b.OwnsOne("Payment.Domain.ValueObjects.AuthorizationCode", "AuthorizationCode", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("AuthorizationCode");

                            b1.HasKey("PaymentIntentId");

                            b1.ToTable("PaymentIntents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.OwnsOne("Payment.Domain.ValueObjects.CardDetails", "CardDetails", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CardBrand");

                            b1.Property<string>("LastFour")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("CardLastFour");

                            b1.Property<string>("Token")
                                .HasColumnType("text")
                                .HasColumnName("CardToken");

                            b1.HasKey("PaymentIntentId");

                            b1.ToTable("PaymentIntents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.OwnsOne("Payment.Domain.ValueObjects.IdempotencyKey", "IdempotencyKey", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("IdempotencyKey");

                            b1.HasKey("PaymentIntentId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("PaymentIntents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("AuthorizationCode");

                    b.Navigation("CardDetails");

                    b.Navigation("GatewayReference");

                    b.Navigation("IdempotencyKey")
                        .IsRequired();

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
