// <auto-generated />
using System;
using Ledger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ledger.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813082054_AddDeadLetterRecords")]
    partial class AddDeadLetterRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ledger.Domain.Entities.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AvailableBalance")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<long>("PendingBalance")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservedBalance")
                        .HasColumnType("bigint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId", "Currency")
                        .IsUnique();

                    b.ToTable("LedgerAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_LedgerAccounts_NonNegativeBalances", "\"AvailableBalance\" >= 0 AND \"PendingBalance\" >= 0 AND \"ReservedBalance\" >= 0");
                        });
                });

            modelBuilder.Entity("Ledger.Domain.Entities.ReconciliationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MismatchCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAccounts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunAtUtc");

                    b.ToTable("ReconciliationReports", (string)null);
                });

            modelBuilder.Entity("Ledger.Infrastructure.DeadLetter.DeadLetterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("DeadLetterRecords");
                });

            modelBuilder.Entity("Ledger.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("InboxMessages");
                });

            modelBuilder.Entity("Ledger.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Processed");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Ledger.Domain.Entities.LedgerAccount", b =>
                {
                    b.OwnsMany("Ledger.Domain.Entities.JournalEntry", "Journal", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreditAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DebitAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("LedgerAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("LedgerAccountId", "Timestamp");

                            b1.ToTable("JournalEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LedgerAccountId");

                            b1.OwnsOne("Ledger.Domain.ValueObjects.CorrelationId", "CorrelationId", b2 =>
                                {
                                    b2.Property<Guid>("JournalEntryId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("CorrelationId");

                                    b2.HasKey("JournalEntryId");

                                    b2.HasIndex("Value")
                                        .IsUnique();

                                    b2.ToTable("JournalEntries");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalEntryId");
                                });

                            b1.OwnsOne("Ledger.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("JournalEntryId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint")
                                        .HasColumnName("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("Currency");

                                    b2.HasKey("JournalEntryId");

                                    b2.ToTable("JournalEntries");

                                    b2.WithOwner()
                                        .HasForeignKey("JournalEntryId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();

                            b1.Navigation("CorrelationId")
                                .IsRequired();
                        });

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("Ledger.Domain.Entities.ReconciliationReport", b =>
                {
                    b.OwnsMany("Ledger.Domain.Entities.ReconciliationLineItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<long>("ActualAvailable")
                                .HasColumnType("bigint");

                            b1.Property<long>("ActualPending")
                                .HasColumnType("bigint");

                            b1.Property<long>("ActualReserved")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<long>("ExpectedAvailable")
                                .HasColumnType("bigint");

                            b1.Property<long>("ExpectedPending")
                                .HasColumnType("bigint");

                            b1.Property<long>("ExpectedReserved")
                                .HasColumnType("bigint");

                            b1.Property<bool>("IsMatch")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ReconciliationReportId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ReconciliationReportId");

                            b1.ToTable("ReconciliationItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReconciliationReportId");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
