events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 ipv6=off valid=30s;

    server {
        listen 80;

        location /identity/ {
            rewrite ^/identity(/.*) $1 break;
            proxy_pass http://identity-api:8080;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /merchant/ {
            rewrite ^/merchant(/.*) $1 break;
            proxy_pass http://merchant-api:8080;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /payment/ {
            rewrite ^/payment(/.*) $1 break;
            proxy_pass http://payment-api:8080;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /ledger/ {
            rewrite ^/ledger(/.*) $1 break;
            proxy_pass http://ledger-api:8080;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /notification/ {
            rewrite ^/notification(/.*) $1 break;
            proxy_pass http://notification-api:8080;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /settlement/ {
            rewrite ^/settlement(/.*) $1 break;
            proxy_pass http://settlement-api:8080;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
