apiVersion: v1
kind: Secret
metadata:
  name: payment-switch-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $db := list "IdentityDb" "MerchantDb" "PaymentDb" "LedgerDb" "NotificationDb" "SettlementDb" }}
  {{ $db }}__ConnectionString: "Host={{ $.Values.config.rabbitmq.hostName }};Port=5432;Database={{ $db }};Username=paymentswitch;Password=paymentswitch"
  {{- end }}
  Jwt__Secret: "your-super-secret-key-minimum-32-bytes!"
  RabbitMQ__Password: "guest"
