// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Settlement.Infrastructure.Persistence;

#nullable disable

namespace Settlement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703152536_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Settlement.Domain.Entities.SettlementBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SettlementBatches");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Settlement.Domain.Entities.SettlementBatch", b =>
                {
                    b.OwnsMany("Settlement.Domain.Entities.Payout", "Payouts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SettlementBatchId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SettlementBatchId");

                            b1.ToTable("Payouts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SettlementBatchId");

                            b1.OwnsOne("Settlement.Domain.ValueObjects.Money", "Fees", b2 =>
                                {
                                    b2.Property<Guid>("PayoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("FeesAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("FeesCurrency");

                                    b2.HasKey("PayoutId");

                                    b2.ToTable("Payouts");

                                    b2.WithOwner()
                                        .HasForeignKey("PayoutId");
                                });

                            b1.OwnsOne("Settlement.Domain.ValueObjects.Money", "GrossVolume", b2 =>
                                {
                                    b2.Property<Guid>("PayoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("GrossAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("GrossCurrency");

                                    b2.HasKey("PayoutId");

                                    b2.ToTable("Payouts");

                                    b2.WithOwner()
                                        .HasForeignKey("PayoutId");
                                });

                            b1.OwnsOne("Settlement.Domain.ValueObjects.Money", "NetAmount", b2 =>
                                {
                                    b2.Property<Guid>("PayoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("NetAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("NetCurrency");

                                    b2.HasKey("PayoutId");

                                    b2.ToTable("Payouts");

                                    b2.WithOwner()
                                        .HasForeignKey("PayoutId");
                                });

                            b1.Navigation("Fees")
                                .IsRequired();

                            b1.Navigation("GrossVolume")
                                .IsRequired();

                            b1.Navigation("NetAmount")
                                .IsRequired();
                        });

                    b.Navigation("Payouts");
                });
#pragma warning restore 612, 618
        }
    }
}
