apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-switch-config
  namespace: payment-switch
data:
  Jwt__Issuer: "IdentityService"
  Jwt__Audience: "PaymentSwitch"
  RabbitMQ__HostName: "rabbitmq"
  RabbitMQ__UserName: "guest"