apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-switch-config
  namespace: payment-switch
data:
  Jwt__Issuer: "IdentityService"
  Jwt__Audience: "PaymentSwitch"
  RabbitMQ__HostName: "rabbitmq"
  EmailVerification__FrontendBaseUrl: "http://localhost:3000"
  PasswordReset__FrontendBaseUrl: "http://localhost:3000"
  PasswordReset__TokenLifetimeHours: "1"
  Smtp__Host: ""
  Smtp__Port: "587"
  Smtp__Username: ""
  Smtp__FromAddress: "noreply@paymentswitch.com"
  Smtp__FromName: "PaymentSwitch"