apiVersion: v1
kind: Secret
metadata:
  name: payment-switch-secret
  namespace: payment-switch
type: Opaque
stringData:
  IdentityDb__ConnectionString: "Host=postgres;Port=5432;Database=IdentityDb;Username=paymentswitch;Password=paymentswitch"
  MerchantDb__ConnectionString: "Host=postgres;Port=5432;Database=MerchantDb;Username=paymentswitch;Password=paymentswitch"
  PaymentDb__ConnectionString: "Host=postgres;Port=5432;Database=PaymentDb;Username=paymentswitch;Password=paymentswitch"
  LedgerDb__ConnectionString: "Host=postgres;Port=5432;Database=LedgerDb;Username=paymentswitch;Password=paymentswitch"
  NotificationDb__ConnectionString: "Host=postgres;Port=5432;Database=NotificationDb;Username=paymentswitch;Password=paymentswitch"
  SettlementDb__ConnectionString: "Host=postgres;Port=5432;Database=SettlementDb;Username=paymentswitch;Password=paymentswitch"
  Jwt__Secret: "your-super-secret-key-minimum-32-bytes!"
  RabbitMQ__Password: "guest"
