using BuildingBlocks.Shared.Aggregate;
using BuildingBlocks.Shared.Events;

namespace BuildingBlocks.Shared.Tests;

public class TestEntity : BaseEntity
{
    public TestEntity() : base() { }
    public TestEntity(Guid id) : base(id) { }
}

public class TestAggregateRoot : AggregateRoot
{
    public TestAggregateRoot() : base() { }
    public TestAggregateRoot(Guid id) : base(id) { }
}

public class DomainEntityTests
{
    private readonly Guid _testId = Guid.NewGuid();

    [Fact]
    public void Equals_SameId_ShouldBeEqual()
    {
        var entity1 = new TestEntity(_testId);
        var entity2 = new TestEntity(_testId);

        Assert.True(entity1.Equals(entity2));
        Assert.True(entity1 == entity2);
    }

    [Fact]
    public void Equals_DifferentId_ShouldNotBeEqual()
    {
        var entity1 = new TestEntity(Guid.NewGuid());
        var entity2 = new TestEntity(Guid.NewGuid());

        Assert.False(entity1.Equals(entity2));
        Assert.True(entity1 != entity2);
    }

    [Fact]
    public void Equals_Null_ShouldReturnFalse()
    {
        var entity = new TestEntity(_testId);

        Assert.False(entity.Equals(null));
        Assert.False(entity == null);
    }

    [Fact]
    public void Equals_SameReference_ShouldBeTrue()
    {
        var entity = new TestEntity(_testId);

        Assert.True(entity.Equals(entity));
    }

    [Fact]
    public void GetHashCode_SameId_ShouldReturnSameHashCode()
    {
        var entity1 = new TestEntity(_testId);
        var entity2 = new TestEntity(_testId);

        Assert.Equal(entity1.GetHashCode(), entity2.GetHashCode());
    }

    [Fact]
    public void OperatorEquals_SameId_ShouldReturnTrue()
    {
        var entity1 = new TestEntity(_testId);
        var entity2 = new TestEntity(_testId);

        Assert.True(entity1 == entity2);
    }

    [Fact]
    public void OperatorNotEquals_DifferentId_ShouldReturnTrue()
    {
        var entity1 = new TestEntity(Guid.NewGuid());
        var entity2 = new TestEntity(Guid.NewGuid());

        Assert.True(entity1 != entity2);
    }

    [Fact]
    public void DomainEvents_NewInstance_ShouldBeEmpty()
    {
        var aggregate = new TestAggregateRoot();

        Assert.Empty(aggregate.DomainEvents);
    }

    [Fact]
    public void AddDomainEvent_ShouldAddToCollection()
    {
        var aggregate = new TestAggregateRoot();
        var domainEvent = new DomainEvent();

        aggregate.AddDomainEvent(domainEvent);

        Assert.Single(aggregate.DomainEvents);
        Assert.Contains(domainEvent, aggregate.DomainEvents);
    }

    [Fact]
    public void ClearDomainEvents_ShouldRemoveAllEvents()
    {
        var aggregate = new TestAggregateRoot();
        aggregate.AddDomainEvent(new DomainEvent());
        aggregate.AddDomainEvent(new DomainEvent());

        aggregate.ClearDomainEvents();

        Assert.Empty(aggregate.DomainEvents);
    }

    [Fact]
    public void DomainEvents_ShouldReturnReadOnlyCopy()
    {
        var aggregate = new TestAggregateRoot();
        aggregate.AddDomainEvent(new DomainEvent());

        var events = aggregate.DomainEvents;

        Assert.False(events is List<DomainEvent>);
        Assert.Throws<NotSupportedException>(() => (events as IList<DomainEvent>)?.Add(new DomainEvent()));
    }

    [Fact]
    public void DomainEvent_ShouldHaveAutoGeneratedId()
    {
        var domainEvent = new DomainEvent();

        Assert.NotEqual(Guid.Empty, domainEvent.Id);
    }

    [Fact]
    public void DomainEvent_ShouldHaveOccurredOn()
    {
        var before = DateTime.UtcNow;
        var domainEvent = new DomainEvent();
        var after = DateTime.UtcNow;

        Assert.InRange(domainEvent.OccurredOn, before, after);
    }
}